PLEASE FIX THIS ERROR
 Error: ./node_modules/@mapbox/node-pre-gyp/lib/util/nw-pre-gyp/index.html
Unknown module type
This module doesn't have an associated type. Use a known file extension, or register a loader for it.

Read more: https://nextjs.org/docs/app/api-reference/next-config-js/turbo#webpack-loaders

Call Stack
5

Hide 5 ignore-listed frame(s)
Object.getCompilationErrors
node_modules/next/src/server/dev/hot-reloader-turbopack.ts (906:25)
DevBundlerService.getCompilationError
node_modules/next/src/server/lib/dev-bundler-service.ts (52:51)
DevServer.getCompilationError
node_modules/next/src/server/dev/next-dev-server.ts (910:38)
DevServer.findPageComponents
node_modules/next/src/server/dev/next-dev-server.ts (874:39)
async DevServer.renderErrorToResponseImpl
node_modules/next/src/server/base-server.ts (4053:18)